/**
 * What to build, as data.
 *
 * **PURE** — a decoded value in, a declaration out, a `TypeError` on anything
 * else. Reading the file is the CLI's job.
 *
 * A build is declared rather than coded because the interesting decision — what
 * a pack is made of — changes far more often than the machinery that assembles
 * it. `packages/core` ships one template today and the app draws six families,
 * so five of them arrive as authored sources; each becomes a template
 * invocation later by editing this file and nothing else.
 *
 * Field names are snake_case, matching the pack format they describe. The
 * parsed shape is camelCase, matching the TypeScript around it. Neither is
 * renamed to match the other, which is the same rule `pack.ts` states next
 * door.
 */

/** Items generated by running a template `count` times. */
export interface TemplateSource {
  readonly kind: "template";
  readonly templateId: string;
  readonly templateVersion: number;
  readonly ladderStep: number;
  readonly count: number;
}

/** Items read from a hand-authored file and lifted into the frozen envelope. */
export interface AuthoredSource {
  readonly kind: "authored";
  /** Relative to the declaration's own location, so a declaration is portable. */
  readonly path: string;
  /**
   * An authored file carries no template, so nothing else can say which skill
   * its items belong to.
   */
  readonly skillId: number;
}

/**
 * Puzzles read from a hand-authored file.
 *
 * **Boards are authored, never generated** — `CLAUDE.md` says so and the
 * reason is where the work goes: proving a board has exactly one solution is a
 * search, and it belongs here, once, rather than on a phone before a player
 * can start.
 */
export interface PuzzleSource {
  readonly kind: "puzzles";
  /** Relative to the declaration, like an authored item source. */
  readonly path: string;
}

export type Source = TemplateSource | AuthoredSource | PuzzleSource;

export interface Declaration {
  readonly packSalt: string;
  /**
   * The first seed. The *n*th generated item takes `seedBase + n`.
   *
   * A `bigint`, because `TemplateRef.seed` is one and the column behind it is a
   * signed `bigint`. JSON has no such type, so the declaration spells it as a
   * string — a JSON number would silently round past 2^53, which is precisely
   * the defect migration 0002 exists to prevent in the pack's own seeds.
   */
  readonly seedBase: bigint;
  readonly issuedAt: string;
  readonly expiresAt: string;
  readonly sources: readonly Source[];
}

const SALT = /^[0-9a-f]{32}$/u;
const INTEGER_STRING = /^-?(0|[1-9][0-9]*)$/u;

function fail(field: string, why: string): never {
  throw new TypeError(`declaration: ${field} ${why}`);
}

function object(value: unknown, field: string): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    fail(field, "must be an object");
  }
  return value as Record<string, unknown>;
}

function requireString(from: Record<string, unknown>, field: string): string {
  const value = from[field];
  if (typeof value !== "string" || value.length === 0) {
    fail(field, "must be a non-empty string");
  }
  return value;
}

function requireInt(
  from: Record<string, unknown>,
  field: string,
  min: number,
  max: number,
): number {
  const value = from[field];
  if (typeof value !== "number" || !Number.isInteger(value) || value < min || value > max) {
    fail(field, `must be an integer between ${min} and ${max}`);
  }
  return value;
}

/**
 * An ISO instant in UTC, validated without touching `Date`.
 *
 * **`new Date(raw)` is the obvious implementation and this package forbids it**
 * — `determinism.test.ts` bans the `Date` identifier outright, and rightly:
 * a module that can construct a date is a module that can read a clock, and
 * the walk cannot tell the two apart. It caught this on the first run.
 *
 * So the shape is a regex and the ranges are arithmetic. The form is pinned
 * exactly — always UTC, always three fractional digits — because the pack
 * format's own `z.iso.datetime()` will see this string and a declaration that
 * parses here but fails there has only moved the error somewhere less helpful.
 */
const INSTANT =
  /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})\.\d{3}Z$/u;

/**
 * How long each month is, with February allowed 29 every year.
 *
 * A declaration is authored by hand and read again by the frozen schema;
 * leap-year arithmetic here would be a second implementation of a calendar for
 * no gain.
 */
const DAYS_IN_MONTH = [31, 29, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31] as const;

function requireInstant(from: Record<string, unknown>, field: string): string {
  const raw = requireString(from, field);
  const parts = INSTANT.exec(raw);
  if (parts === null) {
    fail(field, "must be an ISO 8601 instant in UTC, e.g. 2026-08-18T00:00:00.000Z");
  }
  const [, , month, day, hour, minute, second] = parts.map(Number) as number[];
  const monthLength = DAYS_IN_MONTH[(month as number) - 1];
  const sane =
    (month as number) >= 1 &&
    (month as number) <= 12 &&
    (day as number) >= 1 &&
    monthLength !== undefined &&
    (day as number) <= monthLength &&
    (hour as number) <= 23 &&
    (minute as number) <= 59 &&
    (second as number) <= 59;
  if (!sane) {
    fail(field, "names no such moment");
  }
  return raw;
}

/**
 * **No `skill_id` on a template source.** The template knows which skill it
 * exercises (`Template.skillId`), and `build.ts` resolves it from the
 * registry. A declaration that states it too is a second place to be wrong,
 * and the wrong one would be the pack's — items filed under a skill their
 * template does not exercise, rated against the wrong `user_skills` row.
 * Refused rather than ignored: an ignored field looks like it works.
 */
function refuseSkillIdOnTemplateSource(raw: Record<string, unknown>): void {
  if (raw["skill_id"] !== undefined) {
    fail(
      "skill_id",
      "belongs to the template, not to the source that runs it; remove it",
    );
  }
}

/**
 * One declared source, by its `kind`.
 *
 * `ladder_step` is held to 1–20, matching the frozen item schema. A step
 * outside it produces items the validator refuses, and finding that out at
 * emit time is slower than finding it out here.
 */
function parseSource(value: unknown, index: number): Source {
  const raw = object(value, `sources[${index}]`);
  switch (raw["kind"]) {
    case "template":
      refuseSkillIdOnTemplateSource(raw);
      return {
        kind: "template",
        templateId: requireString(raw, "template_id"),
        templateVersion: requireInt(raw, "template_version", 1, Number.MAX_SAFE_INTEGER),
        ladderStep: requireInt(raw, "ladder_step", 1, 20),
        count: requireInt(raw, "count", 1, 1000),
      };
    case "authored":
      return {
        kind: "authored",
        path: requireString(raw, "path"),
        skillId: requireInt(raw, "skill_id", 1, Number.MAX_SAFE_INTEGER),
      };
    case "puzzles":
      return { kind: "puzzles", path: requireString(raw, "path") };
    default:
      return fail(
        "kind",
        `must be "template", "authored" or "puzzles", not ${JSON.stringify(raw["kind"])}`,
      );
  }
}

export function parseDeclaration(value: unknown): Declaration {
  const raw = object(value, "declaration");

  const packSalt = requireString(raw, "pack_salt");
  if (!SALT.test(packSalt)) {
    fail("pack_salt", "must be 32 lower-case hexadecimal characters");
  }

  const seedRaw = raw["seed_base"];
  if (typeof seedRaw !== "string" || !INTEGER_STRING.test(seedRaw)) {
    fail("seed_base", "must be a decimal integer written as a string");
  }

  const issuedAt = requireInstant(raw, "issued_at");
  const expiresAt = requireInstant(raw, "expires_at");
  if (expiresAt <= issuedAt) {
    fail("expires_at", "must be after issued_at");
  }

  const sources = raw["sources"];
  if (!Array.isArray(sources) || sources.length === 0) {
    fail("sources", "must be a non-empty array");
  }

  return {
    packSalt,
    seedBase: BigInt(seedRaw),
    issuedAt,
    expiresAt,
    sources: sources.map(parseSource),
  };
}
